### ISSUE TITLE
签名后结果好像有问题哎。。。。

### ISSUE THREAD

**Issue by renkang** [kikito/md5.lua#12]
比如data = "cGB2CeC3YmwSWGoVz0kAvQ=="
 签名后得到的摘要是：e133402da1436fc446f6209e697ec981
但是我在别的地方验证却是这个啊： 1f854ddeab80f94b928bd4883ff900b2

**Comment by kikito** [comment]
Hello, I think you are trying to get the md5 of `"cGB2CeC3YmwSWGoVz0kAvQ=="` and getting the wrong result.

Make sure you are using the latest version of the library (*1.1.0*)

```
print(_VERSION) -- Lua 5.2
local md5 = require 'md5'
print(md5._VERSION) -- md5.lua 1.1.0 <============

print(md5.sumhexa("cGB2CeC3YmwSWGoVz0kAvQ==")) -- 9afc2d7e29233a60d0688be6df58380b
