### ISSUE TITLE
Result is not the same when generating MD5 in another way

### ISSUE THREAD

**Issue by kultz** [kikito/md5.lua#13]
Generating using terminal
```
mac:Desktop mac$ echo test | md5
d8e8fca2dc0f896fd7cb4cb0031ba249
```

When i try to implement it using this lib:
```
local md5 = require 'md5'
print(md5.sumhexa("test"))
```
Result would be: **098f6bcd4621d373cade4e832627b4f6**

Am i doing something wrong ?

**Comment by Positive07** [comment]
I'm pretty sure that the md5 hash for test is `098f6bcd4621d373cade4e832627b4f6` so you are probably doing something wrong in the console, it may be adding whitespace or something

**Comment by kultz** [comment]
@Positive07  Yes i find the problem right after i posted it in here:
I probably hashed "test\n" which is included line terminator. Right way is: `echo -n "test" | md5` which is exactly `098f6bcd4621d373cade4e832627b4f6`

**Comment by kikito** [comment]
Ok, closing this issue then 😊
