### ISSUE TITLE
Output differs from md5sum

### ISSUE THREAD

**Issue by zatherz** [kikito/md5.lua#6]
Running on Lua 5.3, sumhexa returns a different value from md5sum.

**Comment by kikito** [comment]
Hi, can you provide more information about this? In particular, which string did you use?

**Comment by zatherz** [comment]
md5sum.lua source code:
    #!/usr/bin/lua
    md5 = require("md5")
    if arg[1] then
            print(md5.sumhexa(arg[1]))
    else
            print("syntax: md5sum.lua <text>")
    end

md5sum.lua output for "test" (without quotes): 098f6bcd4621d373cade4e832627b4f6
/usr/bin/md5sum output for "test" (without quotes): d8e8fca2dc0f896fd7cb4cb0031ba249

Commands used:
* md5sum.lua - lua md5sum.lua test
* /usr/bin/md5sum - echo test | md5sum

**Comment by zatherz** [comment]
After further testing, I've realized that feeding "echo test" to md5sum also includes the newline. Using the -n flag with echo (which is supposed to not put a newline at the end) returns the same result.

This issue can be closed.

**Comment by kikito** [comment]
Thanks a lot, I was a bit worried about this ^__^
