### ISSUE TITLE
I find a bug when text was too long

### ISSUE THREAD

**Issue by shixiaomao** [kikito/md5.lua#7]
when text was too long, the result was not right

**Comment by Positive07** [comment]
Don't open new issues when there is already an open issue that covers yours. Plus this doesn't give enough information at all

**Comment by shixiaomao** [comment]
Sorry, I am unfamiliar with using github.

**Comment by shixiaomao** [comment]
@Positive07 Have you solved this problem

**Comment by kikito** [comment]
Closing this in favor of #4, which is the same issue.
